backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home",
            }
          - { label: Prefix, name: prefix, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Banner Image, name: banner_image, widget: image }
          - { label: Intro text paragraph, name: intro_1, widget: string }
          - { label: Intro text paragraph 2, name: intro_2, widget: string }
          - { label: Features, name: body, widget: markdown }
          - { label: Image 1, name: image_1, widget: image }
          - { label: Image 2, name: image_2, widget: image }
      - file: "content/overview.md"
        label: "Overview"
        name: "overview"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "overview",
            }
          - {
              label: Location description,
              name: location_description,
              widget: text,
            }
          - label: "Amenities"
            name: "amenities"
            widget: list
            fields:
              - { label: Amenity, name: amenity, widget: string }
              - name: details
                label: Amenity details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
          - label: "Nearby"
            name: "nearby"
            widget: list
            fields:
              - { label: Category, name: category, widget: string }
              - name: details
                label: Category details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
          - label: "House Rules"
            name: "house_rules"
            widget: list
            fields:
              - { label: Rule, name: house_rule, widget: string }
              - name: details
                label: Rule details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
      - file: "content/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery",
            }
      - file: "content/map.md"
        label: "Map"
        name: "map"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "map",
            }
      - file: "content/rates.md"
        label: "Rates"
        name: "rates"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "rates",
            }
      - file: "content/reviews.md"
        label: "Reviews"
        name: "reviews"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "reviews",
            }
      - file: "content/availability.md"
        label: "Availability"
        name: "availability"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "availability",
            }
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact",
            }
