backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/home.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home",
            }
          - { label: Prefix, name: prefix, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Banner Image, name: banner_image, widget: image }
          - { label: Intro text paragraph, name: intro_1, widget: text }
          - { label: Intro text paragraph 2, name: intro_2, widget: text }
          - { label: Intro text paragraph 3, name: intro_3, widget: text }
          - { label: Intro text paragraph 4, name: intro_4, widget: text }
          - { label: Intro text paragraph 5, name: intro_5, widget: text }
          - { label: Image 1, name: image_1, widget: image }
          - { label: Image 2, name: image_2, widget: image }
          - { label: Image 3, name: image_3, widget: image }
          - { label: Features, name: features, widget: text }
      - file: "content/overview.md"
        label: "Overview"
        name: "overview"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "overview",
            }
          - {
              label: Location description,
              name: location_description,
              widget: text,
            }
          - { label: Extras, name: body, widget: markdown }
          - label: "Amenities"
            name: "amenities"
            widget: list
            fields:
              - { label: Amenity, name: amenity, widget: string }
              - name: details
                label: Amenity details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
          - label: "Nearby"
            name: "nearby"
            widget: list
            fields:
              - { label: Category, name: category, widget: string }
              - name: details
                label: Category details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
          - label: "House Rules"
            name: "house_rules"
            widget: list
            fields:
              - { label: Rule, name: house_rule, widget: string }
              - name: details
                label: Rule details
                widget: list
                fields:
                  - { name: detail, label: Detail, widget: string }
      - file: "content/gallery.md"
        label: "Gallery"
        name: "gallery"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "gallery",
            }
          - {
              label: "Add additional images for Gallery",
              name: "galleryImages",
              widget: "list",
              summary: "{{fields.image}}",
              field: { label: Image, name: image, widget: image },
            }
      - file: "content/rates.md"
        label: "Rates"
        name: "rates"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "rates",
            }
          - label: "Rates"
            name: "rates"
            widget: list
            fields:
              - { label: Season, name: season, widget: string }
              - { label: Start, name: start, widget: string }
              - { label: End, name: end, widget: string }
              - { label: Nightly, name: nightly, widget: string }
              - { label: Min nights, name: minNight, widget: string }
      - file: "content/bookings.md"
        label: "Bookings"
        name: "bookings"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "bookings",
            }
          - label: "Booking info"
            name: "booking_info"
            widget: text
      - file: "content/contact.md"
        label: "Contact"
        name: "contact"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact",
            }
